export const experience = [
  {
    company: "Techbae",
    companyName: "Techbae",
    period: "December 2020 to January 2021",
    position: "Full-Stack Engineer",
    skills: [
      "ReactJS",
      "VueJS",
      "NuxtJS",
      "NodeJS",
      "Express",
      "Mongoose",
      "Redux",
    ],
    about: `I worked as a full stack developer, handling diverse projects and crafting content management systems (CMS) for various websites. \n\nMy role involved comprehensive development tasks, ensuring seamless functionality and user-friendly interfaces.`,
    color: "#FDEED3",
  },
  {
    company: "Zenius",
    companyName: "Zenius",
    period: "January 2021 to July 2021",
    position: "Front-end Engineer",
    skills: ["ReactJS", "Typescript", "Redux"],
    img: "/companyIcons/zenius_logo.jpg",
    about: `I served as a front-end developer for an Indonesian education platform, where my responsibilities included maintaining a group video call system integral to the platform's functionality. This role allowed me to contribute significantly to the user interface and enhance the overall user experience for the educational community.`,
    color: "#FFDFB7",
  },
  {
    company: "Teraoka",
    companyName: "Teraoka Seiko",
    period: "July 2021 to September 2023",
    position: "Full-Stack Engineer",
    skills: [
      "ReactJS",
      "Typescript",
      "Redux",
      "Github Actions",
      "Fastlane",
      "Android Studio",
      "Xcode",
    ],
    img: "/companyIcons/teraoka_logo.webp",
    about: `The first company I worked at in Japan, I worked on maintaining a smartphone app "Shop&Go". I worked on the content management system on the front end,  the development of some aspects of the android version of the app, and created an automated release workflow for the app on both the Apple App Store and the Android Play Store.`,
    color: "#FFCBA6",
  },
  {
    company: "BitA",
    companyName: "BitA",
    period: "October 2023 to Now",
    position: "Technical Lead, Front-end Engineer",
    skills: [
      "ReactJS",
      "Typescript",
      "Redux",
      "Github Actions",
      "Various CMS's",
    ],
    img: "/companyIcons/bita_logo.svg",
    about: `In my current position, I work as a Technical lead of the front end, and a front-end engineer on multiple projects.`,
    color: "#EFEFF2",
  },
];
