export const experience = [
  {
    company: "Techbae",
    companyName: "Techbae",
    period: "December 2020 to January 2021",
    position: "Full-Stack Engineer",
    skills: [
      "ReactJS",
      "VueJS",
      "NuxtJS",
      "NodeJS",
      "Express",
      "Mongoose",
      "Redux",
    ],
    about: ``,
    color: "#FDEED3",
  },
  {
    company: "Zenius",
    companyName: "Zenius",
    period: "January 2021 to July 2021",
    position: "Front-end Engineer",
    skills: ["ReactJS", "Typescript", "Redux"],
    img: "/companyIcons/zenius_logo.jpg",
    about: ``,
    color: "#FFDFB7",
  },
  {
    company: "Teraoka",
    period: "July 2021 to September 2023",
    position: "Full-Stack Engineer",
    skills: [
      "ReactJS",
      "Typescript",
      "Redux",
      "Github Actions",
      "Fastlane",
      "Android Studio",
      "Xcode",
    ],
    img: "/companyIcons/teraoka_logo.webp",
    about: ``,
    color: "#FFCBA6",
  },
  {
    company: "BitA",
    period: "October 2023 to Now",
    position: "Full-Stack Engineer",
    skills: ["ReactJS", "Typescript", "Redux", "Github Actions"],
    img: "/companyIcons/bita_logo.svg",
    about: ``,
    color: "#EFEFF2",
  },
];
